version: "3.8"
services:
  # =========================
  # SERVICIO DE USUARIOS (Autenticación)
  # =========================
  users-service:
    image: users-service:${TAG:-latest}
    build: ./users-service
    container_name: users-service
    env_file:
      - ./users-service/.env
    expose:
      - "3001"
    networks:
      - backend-net

  # =========================
  # SERVICIO ACADÉMICO (Cursos)
  # =========================
  academic-service:
    image: academic-service:${TAG:-latest}
    build: ./academic-service
    container_name: academic-service
    env_file:
      - ./academic-service/.env
    expose:
      - "3002"
    networks:
      - backend-net
  # =========================
  # API Gateway
  # =========================
  api-gateway:
    image: api-gateway:${TAG:-latest}
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - users-service
      - academic-service
    networks:
      - backend-net

  # =========================
  # Frontend (SPA React)
  # =========================
  frontend:
    image: frontend:${TAG:-latest}
    build: ../frontend    
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - api-gateway
    networks:
      - backend-net
networks:
  backend-net:
    driver: bridge
